# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - stop
    - move_forward
    - turn_left
    - turn_right
    - found
  - /habitat/task/measurements:
    # - num_steps
    # - distance_to_goal
    # - success
    # - spl
    # - soft_spl
    # - top_down_map
    - distance_to_curr_goal
    - distance_to_multi_goal
    - sub_success
    - success
    - episode_length
    - mspl
    - percentage_success
    - ratio
    - pspl
    - raw_metrics
  - /habitat/task/lab_sensors:
    - pointgoal_with_gps_compass_sensor
    - compass_sensor
    - gps_sensor
    - heading_sensor
    - multiobjectgoal
  - /habitat/dataset: dataset_config_schema
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat_baselines/rl/policy/obs_transforms@habitat_baselines.rl.policy.main_agent.obs_transforms.resize_shortest_edge: resize_shortest_edge_base
  - /habitat_baselines/rl/policy/obs_transforms@habitat_baselines.rl.policy.main_agent.obs_transforms.center_cropper: center_cropper_base
  - _self_

habitat:
  seed: 99
  task:
    success_reward: 2.5
    slack_reward: -1e-3
    type: MultiNav-v1
    end_on_success: True
    reward_measure: success
    success_measure: success
    goal_sensor_uuid: multiobjectgoal
    measurements:
      # distance_to_goal:
      #   distance_to: POINT
      success:
        success_distance: 1.5

  dataset:
    type: MultiNav-v1
    split: train
    scenes_dir: data/scene_datasets
    data_path: data/datasets/multinav/3_ON/{split}/{split}.json.gz

  environment:
    max_episode_steps: 50
    iterator_options:
      max_scene_repeat_steps: 50000
      # group_by_scene: False
      # max_scene_repeat_episodes: 1

  simulator:
    additional_object_paths: [ data/objects ]
    forward_step_size: 0.25
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          depth_sensor:
            min_depth: 0.
            width: 256
            height: 256
            hfov: 90
            position: [0, 0.88, 0]
          rgb_sensor:
            width: 256
            height: 256
            hfov: 90
            position: [0, 0.88, 0]
        height: 0.88
        radius: 0.1

    habitat_sim_v0:
      gpu_device_id: 0

habitat_baselines:
  trainer_name: "ddppo"
  torch_gpu_id: 0
  task_name: multinav
  # Visualization settings
  video_dir: "video_dir/multion/"
  # writer_type: wb # to deactivate just comment this
  wb:
    entity: ziliottofilippodev
    project_name: NavProg
    run_name: multion
  save_obs:
    save_to_disk: True 
  sampling_strategy: "unreachable"

  # Object Detector settings
  object_detector:
    use_detector: True
    type: "owl-vit2"
    size: "base"
    thresh: 0.2
    nms_thresh: 0.5
    store_detections: False
    use_detection_cls: True
    detection_cls_thresh: 0.2
    # Additional object detector settings
    use_additional_detector: False
    additional_type: "detr"
    additional_size: "resnet101"
    additional_thresh: 0.9
    additional_nms_thresh: 0.5

  # Value Mapper settings
  value_mapper:
    use_value_mapper: True
    type: "blip"
    size: "base"
    visualize: True
    save_video: False
    policy: "v1"
    exploration_threshold: 0.2
    min_obstacle_height: 0.15
    max_obstacle_height: 0.88
    use_max_confidence: False
    map_size: 500
    pixels_per_meter: 10
    save_image_embed: False
    th_memory: 0.4

  # Eval settings
  # Distance detection threshold (when the agent should call stop action)
  # This value is then added to the agent radius (e.g. 0.5 + 0.18 )
  object_distance_threshold: 0.3
  # To evaluate on all episodes, set this to -1
  test_episode_count: 5 # n° of evaluation episodes
  eval_ckpt_path_dir: "data/new_checkpoints/pointnav/hm3d-depth/"
  num_environments: 1
  checkpoint_folder: "data/new_checkpoints/pointnav/hm3d-depth/"
  num_updates: -1
  total_num_steps: 2.5e9
  log_interval: 10
  num_checkpoints: 100
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True
  evaluate: True
  load_resume_state_config: False
  verbose: False
  eval_keys_to_include_in_name: []
  eval:
  # minival: 30 episodes , val: 1000 episodes
    split: val
    should_load_ckpt: False
    use_ckpt_config: False
    # video_option: [ "disk" ]

  rl:
    policy:
      main_agent:
        name: "PointNavResNetPolicy"
    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 2
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.01
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 128
      hidden_size: 512
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: False
      use_linear_lr_decay: False
      reward_window_size: 50
      use_normalized_advantage: False

      # Use double buffered sampling, typically helps
      # when environment time is similar or large than
      # policy inference time during rollout generation
      use_double_buffered_sampler: False

    ddppo:
      sync_frac: 0.6
      # The PyTorch distributed backend to use
      distrib_backend: NCCL
      # Visual encoder backbone
      # pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      pretrained_weights: data/ddppo-models/hm3d-depth/ckpt_60.pth
      # Initialize with pretrained weights
      pretrained: True
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: True
      # Whether the visual encoder backbone will be trained.
      train_encoder: False
      # Whether to reset the critic linear layer
      reset_critic: False

      # Model parameters
      backbone: resnet50
      rnn_type: LSTM
      num_recurrent_layers: 2
